### PR TITLE
feat(profile): preview currently displaying presence

### PR DESCRIPTION
**Pull request by kyrie25**
- Preview currently displaying presence in Profile card
- Add GIF support for profile images

### CODE REVIEW

**Comment by dead8309** [comment]
I don't think this is needed given that profile screen would be removed/replaced in future with logout options in the sidebar itself

**Comment by kyrie25** [comment]
> I don't think this is needed given that profile screen would be removed/replaced in future with logout options in the sidebar itself

That's a shame. Is there any reason for the change though, besides removing the route itself?

**Comment by dead8309** [comment]
> Is there any reason for the change though, besides removing the route itself?

Its getting difficult to maintain parity with the original one also its not in the scope of the project to provide this feature

**Comment by kyrie25** [comment]
> Its getting difficult to maintain parity with the original one also its not in the scope of the project to provide this feature
> 
> 

There most likely won't be any more changes to the presence layout itself so there won't be a need to maintain it as much
But if it's not needed then feel free to close this PR 👌

**Comment by dead8309** [comment]
Oh no there are some problems with the current preview system like showing errors if the user has a discord link in their button urls, unicodes in name, validation related things that i was talking about which is difficult to maintain.

Also we shouldn't try to add more IO operations in the rpc like saving current configs to prefs etc which can impact performace and is not an important requirement.

Thanks for the pr but i wont be able to merge it. I hope you understand

**Pull request closed without merging**
