### PR TITLE
chore(media-rpc): delocalize artist name

### PR DESCRIPTION
**Pull request by kyrie25**
Small PR, just some nitpicking

### CODE REVIEW

**Comment by dead8309** [comment]
by is actually required that's how Spotify does it

**Comment by dead8309** [comment]
Screenshot_20241018-161206_Discord
I think I have to update discord

**Comment by dead8309** [comment]
It shows `by` and `on` both

**Comment by kyrie25** [comment]
> It shows `by` and `on` both

The latest layout by Discord doesn't include both, so which one would you wanna follow through tho

**Comment by dead8309** [comment]
Latest one ofc

**Comment by kyrie25** [comment]
> Latest one ofc

Makes sense. Cheers!

**Pull request merged**
