### PR TITLE
feat(custom-rpc): correctly display preview & match Discord layout

### LINKED ISSUE #224: 24 hr format for timestamps
I'd like to have a 24-hour format option instead of the 12-hour format in the app(according to which one the system uses)  Because the two formats are different, it can be confusing for users who are not familiar with the 12-hour format.
¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯
 

Google Keep Notes has this feature.
Screenshot_20231012-133405
Screenshot_20231012-133633

### PR DESCRIPTION
**Pull request by kyrie25**
- Match Discord activity layout
- Use timestamp from Custom RPC data and display time properly
- Follow system settings on time picker and option to switch layout
Resolves #224 
- Show error on saving config with empty name (#279)

<details>
<summary>Profile preview update</summary>

image
image
image

</details>

### CODE REVIEW

**Comment by MegaSa1nt** [comment]
bro came out of nowhere and truly revived his app lol

**Comment by kyrie25** [comment]
> bro came out of nowhere and truly revived his app lol

It's not dead if I'm using it 🦅

**Comment by MegaSa1nt** [comment]
Based

**Comment by dead8309** [comment]
Ill take a look at this today

**Comment by kyoyacchi** [comment]
good job bro. Helal sana.

**Pull request merged**
