### PR TITLE
feat: use external proxy for images

### PR DESCRIPTION
**Pull request by kyrie25**
## Switching from `mp:attachments` to `mp:external`

From my understanding of the code base, and this comment block:
https://github.com/dead8309/Kizzy/blob/25cec8896dc644af281a27113a2172b92f5fbd81/data/src/main/java/com/my/kizzy/data/rpc/KizzyRPC.kt#L105-L117

Kizzy currently sends images as whole binaries to a Cloudflare Worker, the worker would then download the image and uploads it back to a channel, receiving an `mp:attachments` proxy URL in the end. This is very resource-intensive for the worker as **all images needs to be handled through one shared worker**, especially as the app scales upwards. The current stability of the current method is also very inconsistent, with images not being sent every 3-4 song changes in Media RPC.

This PR aims to delegate the image processing task to a 3rd-party service (Imgur) handled client-side and only have the worker process the proxied `mp:external` URL to the Discord Gateway. This should drastically reduce the workload of the worker and improve the stability & speed of the feature. This would also cut having to download an image from an already-accessible URL in Custom RPC.

Some notes about the codes in this PR:
- The Client ID used for Imgur API is their web client ID used to send images *without* an account. This Client ID can be found in their web client source code.
  - It has been publicized and remains constant for at least >5 years at the time of this PR creation, with [commits found using it as old as 2019](https://github.com/rokups/virtual-reality/commit/e2f86f04f1cfe77b4c4fb353b9ea214d6627e8e6#diff-d59f4b5af762fd5741a709ca624ee639335ba3e7c371f9772cba962211641514), and [having been featured in a HackerOne report](https://hackerone.com/reports/1058427). Regardless, they still have not updated it (lol)
  - There should be no worries of rate-limiting because:
    1. The Client ID is used on the entirety of their website
    2. Kizzy automatically resends the request on server error as it tries to update the presence
- The API endpoint used to external assets **only** handles **getting the external thumbnail** and stores no additional info (as it only receives the image URL). 
   - Unfortunately, I can't open-source my API repository because there are private contents, but essentially this is the entire endpoint:
```ts
        try {
            new URL(String(url));
        } catch (e) {
            return res.status(400).send({ error: "Invalid URL!" });
        }

        const message = await axios.post(
            `https://discord.com/api/v10/channels/${CHANNEL_ID}/messages`,
            {
                content: url,
            },
            {
                headers: {
                    Authorization: `Bot ${process.env.BOT_TOKEN}`,
                },
            },
        );

        // Wait for Discord to process the message
        await new Promise(resolve => setTimeout(resolve, 1000));

        const messageData = await axios.get(
            `https://discord.com/api/v10/channels/${CHANNEL_ID}/messages/${message.data.id}`,
            {
                headers: {
                    Authorization: `Bot ${process.env.BOT_TOKEN}`,
                },
            },
        );

        if (!messageData.data.embeds?.[0]?.thumbnail?.proxy_url) {
            console.log(messageData.data);

            await axios.delete(`https://discord.com/api/v10/channels/${CHANNEL_ID}/messages/${message.data.id}`, {
                headers: {
                    Authorization: `Bot ${process.env.BOT_TOKEN}`,
                },
            });

            return res.status(500).send({ error: "No valid image" });
        }

        await axios.delete(`https://discord.com/api/v10/channels/${CHANNEL_ID}/messages/${message.data.id}`, {
            headers: {
                Authorization: `Bot ${process.env.BOT_TOKEN}`,
            },
        });

        res.status(200).send({
            url: messageData.data.embeds[0].thumbnail.proxy_url.replace("https://images-ext-1.discordapp.net/", "mp:"),
        });
```
Please feel free to **commit changes of the new worker endpoints directly to this branch**

### CODE REVIEW

**Comment by dead8309** [comment]
Thank you for your proposal to improve image handling.I do believe our current implementation is more efficient

1. We just stream images from Cloudflare Worker to discord without full downloads.
2. We currently uses one API call, whereas the proposed change requires two for image uploads.
3. We use webhooks, not bot accounts, for uploads to allow for higher rate limits and easy load distribution if needed.
4. We are trying to avoid as much third-party services as we can.
5. Workers scale automatically thats why i migrated to it


I'm open to further discussion on this.

**Comment by kyrie25** [comment]
Thanks for the clarification, I'll make some of my points clear too:

> We currently uses one API call, whereas the proposed change requires two for image uploads.

The number of calls aren't relevant in my opinion (though the number is already small and only requires to be done every 3-5 minutes on average), as the time and workload it requires for each tasks matters more. 

Currently Kizzy requires one API call because the all is handled server-side via one endpoint, both image streaming from both ends and communication with Discord Gateway.
If Kizzy were to delegate image uploading to Imgur's public services, the worker would only need to handle receiving one string/URL to get the proxy image link. 
Client-side performance remains unimpacted while server-side workload/worktime is significantly reduced.

There is also the concern of reliability as images are very often missing with the current implementation as users reported and having experienced it myself. Of course in production we can't say for sure, but Imgur's reliability as a public service is a good base and reason to delegate the task.

> We use webhooks, not bot accounts, for uploads to allow for higher rate limits and easy load distribution if needed.

What I posted only serves as a demo of course, the idea still remains: Getting the image proxy from Discord
It is up to your implementation on the worker's side if you were to accept the proposal. I used REST APIs because it is already at hand.

> We are trying to avoid as much third-party services as we can.

I understand the concern, but in this case its neither of performance nor privacy. Imgur needs no introduction and are also specialized at the task. It was also utilized extensively by other RPC services such as PreMiD for a very long period of time (having worked there professionally myself) before moving on to their own CDN for ease of development.

As I'm seeing it right now, there are good reasons to give it a shot but of course, if the current implementation is better, I would happily close this proposal. 
Let me know what you think, cheers!

**Comment by dead8309** [comment]
Thanks for the proposal and explanation. However, I’ve decided not to move forward with this change. The current Cloudflare Worker setup provides better control, scalability.

**Comment by kyrie25** [comment]
That's fair, thank you for your time!

**Comment by kyrie25** [comment]
> The current Cloudflare Worker setup provides better control, scalability.

@dead8309  Upon further research it turns out you do **NOT** need a Worker to use Discord's image proxy as you can leverage Discord's Game SDK endpoints.
```url
POST https://discord.com/api/v10/applications/<app-id>/external-assets
```
image

This method is officially used for Game SDK external assets.
3rd-party image hosting providers are still needed, but this also means users can **choose a provider of choice** in case one goes down/are blocked in their region.

Let me know what you think!

**Comment by kyrie25** [comment]
> That's great! Will it require users token for authorization ?

Yes unfortunately, but since Kizzy already has that there would be no change on the user's flow.

**Comment by kyrie25** [comment]
Worth noting that this endpoint is what the **Discord Desktop client** uses when a game calls `SET_PRESENCE` locally.

This means no rate limiting nor abuse in any way.

**Comment by dead8309** [comment]
Still i don't think it's a good idea. I want to avoid as much api requests which requires a token even tho it doesn't have a rate limit now but if added in future could break a lot of things for us

**Comment by kyrie25** [comment]
> Still i don't think it's a good idea. I want to avoid as much api requests which requires a token

This would actually reduce the amount of requests if you consider the following:
1. `mp:attachment` URLs can still be used,
2. Both `mp:external` and 3rd-party URLs **never** expires, which means Kizzy will not have to dump cache like it does currently.
3. It is an official Discord API used on a daily basis in the Discord client, with caching on their end.

> if added in future could break a lot of things for us

Can you elaborate on what this could break?
From what I'm seeing this would help with a lot of prevalent issues with connection timeouts/ISP blocks the more services Kizzy can implement for image hosting

**Comment by kyrie25** [comment]
Improving caching album art cover from per-song to a per-album basis would also help with the issue you mentioned

https://github.com/kyrie25/Kizzy/blob/use-external-url/data/src/main/java/com/my/kizzy/data/get_current_data/media/GetCurrentlyPlayingMedia.kt#L82

Let me know what you think!

**Comment by dead8309** [comment]
I think instead to replacing everything at once

Add the Imgur proxy feature behind advanced setting with default set to off and add do the Imgur upload logic only if it's turned on.

Create new functions in ApiService. if it remains stable for some time it will eventually replace the existing one

**Pull request closed without merging**
