### PR TITLE
fix(api): catch errors

### PR DESCRIPTION
**Pull request by kyrie25**
As title

### CODE REVIEW

**Comment by dead8309** [comment]
We already have a logger for HttpClient here 
https://github.com/dead8309/Kizzy/blob/e19dbe78e701edd14fbcba7ab5e51f45c89d7491/data/src/main/java/com/my/kizzy/data/di/AppModule.kt#L77-L85

**Comment by kyrie25** [comment]
> We already have a logger for HttpClient here 
> https://github.com/dead8309/Kizzy/blob/e19dbe78e701edd14fbcba7ab5e51f45c89d7491/data/src/main/java/com/my/kizzy/data/di/AppModule.kt#L77-L85

It logs but will still throw errors and can crash the entire app


This is reproducible if you set timeout duration to 1 to emulate timeout requests

**Comment by dead8309** [comment]
you can handle errors but don't inject/use logger there, maybe tweak the HttpClient's logger settings to include more information

**Comment by kyrie25** [comment]
My bad, it *doesn't* log if connection fails (i.e. any errors besides a HTTP error)

**Pull request merged**
